import { describe, expect, it } from 'vitest'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const panelPath = path.resolve(__dirname, '../../src/renderer/components/embedded-agent/EmbeddedAgentPanel.vue')
const adapterPath = path.resolve(__dirname, '../../src/renderer/components/embedded-agent/hydro-agent-api-adapter.js')
const embeddedFilesPath = path.resolve(__dirname, '../../src/renderer/composables/useEmbeddedAgentFiles.js')
const workspacePanelPath = path.resolve(__dirname, '../../src/renderer/components/workspace-files/WorkspaceFilePanel.vue')
const hydrologyMainPath = path.resolve(__dirname, '../../src/renderer/pages/hydrology-workbench/main.js')
const hydrologyHtmlPath = path.resolve(__dirname, '../../src/renderer/pages/hydrology-workbench/index.html')
const agentChatTabPath = path.resolve(__dirname, '../../src/renderer/pages/main/components/AgentChatTab.vue')
const useAgentChatPath = path.resolve(__dirname, '../../src/renderer/composables/useAgentChat.js')
const filesTabPath = path.resolve(__dirname, '../../src/renderer/pages/main/components/RightPanel/tabs/FilesTab.vue')
const preloadPath = path.resolve(__dirname, '../../src/preload/preload.js')

describe('embedded agent panel wiring', () => {
  it('reuses the existing AgentChatTab instead of custom chat rendering', () => {
    const source = fs.readFileSync(panelPath, 'utf-8')

    expect(source).toContain("AgentChatTab from '@/pages/main/components/AgentChatTab.vue'")
    expect(source).toContain('window.hydroAgent.connect')
    expect(source).toContain('window.hydroAgent.listSessions()')
    expect(source).toContain('findLatestSession')
    expect(source).toContain('reopenSessionIfNeeded')
    expect(source).toContain('reopenAgentSession')
    expect(source).toContain('embedded-agent:last-session:')
    expect(source).toContain('window.localStorage.getItem')
    expect(source).toContain('window.localStorage.setItem')
    expect(source).toContain('createHydroAgentApiAdapter')
    expect(source).toContain('window.electronAPI.getEmbeddedAppPreferences')
    expect(source).toContain('window.electronAPI.updateEmbeddedAppPreferences')
    expect(source).toContain('window.electronAPI.listAPIProfiles')
    expect(source).toContain('persistAppPreferences')
    expect(source).toContain(':api-profile-id="currentApiProfileId"')
    expect(source).toContain(':model-id="currentModelId"')
    expect(source).toContain('@api-profile-selected="handleApiProfileSelected"')
    expect(source).toContain("const nextProfileId = typeof payload === 'string'")
    expect(source).toContain("const nextModelId = typeof payload?.modelId === 'string'")
    expect(source).not.toContain('await agentApi.value.switchAgentApiProfile')
    expect(source).toContain('<div v-if="appLabel || title" class="embedded-agent-title">')
    expect(source).toContain('border-radius: 10px;')
    expect(source).toContain('height: 34px;')
    expect(source).toContain("Icon from '@components/icons/Icon.vue'")
    expect(source).toContain('showContextTip')
    expect(source).toContain('contextTipStyle')
    expect(source).toContain('getBoundingClientRect')
    expect(source).toContain('title="当前上下文"')
    expect(source).toContain('<Icon name="info"')
    expect(source).not.toContain('top: 126px;')
    expect(source).not.toContain('right: 24px;')
    expect(source).toContain('title="当前会话能力"')
    expect(source).toContain('<Icon name="sliders"')
    expect(source).toContain('title="新建会话"')
    expect(source).toContain('<Icon name="plus"')
    expect(source).not.toContain('class="context-send-btn"')
    expect(source).not.toContain('class="embedded-agent-context"')
    expect(source).toContain(':agent-api="agentApi"')
    expect(source).toContain(':weixin-notify-api="weixinNotifyApi"')
    expect(source).toContain('const weixinNotifyApi = computed(() => {')
    expect(source).toContain('listWeixinNotifyTargets: api.listWeixinNotifyTargets?.bind(api)')
    expect(source).toContain('sendWeixinNotifyText: api.sendWeixinNotifyText?.bind(api)')
    expect(source).toContain('@model-selected="handleModelSelected"')
    expect(source).toContain('@request-clear-session="handleClearSession"')
    expect(source).toContain('contextProvider')
    expect(source).toContain("WorkspaceFilePanel from '@components/workspace-files/WorkspaceFilePanel.vue'")
    expect(source).toContain("useEmbeddedAgentFiles(agentApi)")
    expect(source).toContain("activeTab = ref('chat')")
    expect(source).toContain("activeTab === 'files'")
    expect(source).toContain('工作目录')
    expect(source).toContain(':save-text-handler="handleEmbeddedFileSave"')
    expect(source).toContain('@insert-path="handleInsertPath"')
    expect(source).toContain('chatRef.value?.insertText?.(`${path}\\n`)')
    expect(source).toContain('embeddedFiles.setSessionId(nextSessionId)')
    expect(source).toContain('setCurrentAgentSession')
  })

  it('maps AgentChatTab agent API calls onto the embedded hydroAgent bridge', () => {
    const source = fs.readFileSync(adapterPath, 'utf-8')

    expect(source).toContain('createAgentSession: (options) => hydroAgent.createSession(options)')
    expect(source).toContain('switchAgentApiProfile: ({ sessionId, profileId }) => hydroAgent.switchApiProfile(sessionId, profileId)')
    expect(source).toContain('clearAndRecreateAgentSession')
    expect(source).toContain('setCurrentAgentSession: (sessionId) => hydroAgent.setCurrentSession(sessionId)')
    expect(source).toContain('sendAgentMessage: ({ sessionId, message, model, modelTier, maxTurns }) =>')
    expect(source).toContain('hydroAgent.onEvent(null')
    expect(source).toContain("'agent:message': 'onAgentMessage'")
    expect(source).toContain("'agent:stream': 'onAgentStream'")
    expect(source).toContain('saveAgentFile: ({ sessionId, relativePath, content }) =>')
    expect(source).toContain('createAgentFile: ({ sessionId, parentPath, name, isDirectory }) =>')
    expect(source).toContain('renameAgentFile: ({ sessionId, oldPath, newName }) =>')
    expect(source).toContain('deleteAgentFile: ({ sessionId, path }) =>')
    expect(source).toContain('searchAgentFiles: ({ sessionId, keyword, showHidden }) =>')
    expect(source).toContain('openAgentFile: ({ sessionId, relativePath }) =>')
    expect(source).toContain('openAgentOutputDir: (sessionId) =>')
  })

  it('reuses the shared workspace file panel through the embedded adapter', () => {
    const embeddedFilesSource = fs.readFileSync(embeddedFilesPath, 'utf-8')
    const workspacePanelSource = fs.readFileSync(workspacePanelPath, 'utf-8')
    const filesTabSource = fs.readFileSync(filesTabPath, 'utf-8')

    expect(embeddedFilesSource).toContain("import { useWorkspaceFiles } from './useWorkspaceFiles'")
    expect(embeddedFilesSource).toContain('listAgentDir')
    expect(embeddedFilesSource).toContain('readAgentFile')
    expect(embeddedFilesSource).toContain('createAgentFile')
    expect(embeddedFilesSource).toContain('renameAgentFile')
    expect(embeddedFilesSource).toContain('deleteAgentFile')
    expect(embeddedFilesSource).toContain('searchAgentFiles')
    expect(embeddedFilesSource).toContain('openAgentOutputDir')
    expect(workspacePanelSource).toContain('defineExpose({')
    expect(workspacePanelSource).toContain('saveTextHandler')
    expect(workspacePanelSource).toContain('allowMutations')
    expect(workspacePanelSource).toContain('FileTreeHeader')
    expect(workspacePanelSource).toContain('FilePreview')
    expect(filesTabSource).toContain(':save-text-handler="handleProjectFileSave"')
    expect(filesTabSource).toContain('window.electronAPI.saveProjectFile')
    expect(filesTabSource).not.toContain('saveAbsoluteFile')
  })

  it('lets embedded hosts send current business context through AgentChatTab', () => {
    const source = fs.readFileSync(agentChatTabPath, 'utf-8')
    const composableSource = fs.readFileSync(useAgentChatPath, 'utf-8')

    expect(source).toContain('agentApi:')
    expect(source).toContain('agentApi: props.agentApi')
    expect(source).toContain('weixinNotifyApi:')
    expect(source).toContain(':weixin-notify-api="weixinNotifyApi"')
    expect(source).toContain("'api-profile-selected'")
    expect(source).toContain(':show-api-profile-switcher="Boolean(props.sessionId)"')
    expect(source).toContain('@api-profile-selected="handleApiProfileSelected"')
    expect(source).toContain("emit('model-selected', { modelId: normalizedModelId })")
    expect(composableSource).toContain('const agentApi = options.agentApi')
    expect(composableSource).toContain('await agentApi.sendAgentMessage(sendOptions)')
    expect(source).toContain('sendMessage: (text) => handleSend(text)')
  })

  it('keeps hydroAgent sendMessage options when bridging embedded requests', () => {
    const source = fs.readFileSync(preloadPath, 'utf-8')

    expect(source).toContain('payload.options || {}')
    expect(source).toContain('payload.model || payload.modelTier || payload.options?.model')
    expect(source).toContain("ipcRenderer.invoke('hydro-agent:clearAndRecreate'")
    expect(source).toContain("ipcRenderer.invoke('hydro-agent:setCurrentSession'")
    expect(source).toContain("ipcRenderer.invoke('hydro-agent:createFile'")
    expect(source).toContain("ipcRenderer.invoke('hydro-agent:renameFile'")
    expect(source).toContain("ipcRenderer.invoke('hydro-agent:deleteFile'")
    expect(source).toContain("ipcRenderer.invoke('hydro-agent:openFile'")
    expect(source).toContain("ipcRenderer.invoke('hydro-agent:openOutputDir'")
  })

  it('passes injected weixin notification API into the shared chat toolbar', () => {
    const agentChatTabSource = fs.readFileSync(agentChatTabPath, 'utf-8')
    const chatInputSource = fs.readFileSync(path.resolve(__dirname, '../../src/renderer/pages/main/components/agent/ChatInput.vue'), 'utf-8')
    const toolbarSource = fs.readFileSync(path.resolve(__dirname, '../../src/renderer/pages/main/components/agent/ChatInputToolbar.vue'), 'utf-8')

    expect(agentChatTabSource).toContain(':weixin-notify-api="weixinNotifyApi"')
    expect(chatInputSource).toContain(':weixin-notify-api="weixinNotifyApi"')
    expect(toolbarSource).toContain('weixinNotifyApi:')
    expect(toolbarSource).toContain('const resolvedWeixinNotifyApi = computed(() => props.weixinNotifyApi || window.electronAPI || null)')
    expect(toolbarSource).toContain('weixinApi.listWeixinNotifyTargets()')
    expect(toolbarSource).toContain('weixinApi.sendWeixinNotifyText({')
  })

  it('mounts the reusable panel inside hydrology workbench', () => {
    const mainSource = fs.readFileSync(hydrologyMainPath, 'utf-8')
    const htmlSource = fs.readFileSync(hydrologyHtmlPath, 'utf-8')
    const hydrologyAgentPanelSource = fs.readFileSync(path.resolve(__dirname, '../../src/renderer/pages/hydrology-workbench/agent-panel.js'), 'utf-8')

    expect(htmlSource).toContain('id="hydrologyAgentPanel"')
    expect(mainSource).toContain("mountHydrologyAgentPanel")
    expect(hydrologyAgentPanelSource).toContain("appId: 'hydrology-workbench'")
    expect(hydrologyAgentPanelSource).toContain("appLabel: ''")
    expect(hydrologyAgentPanelSource).toContain("title: ''")
    expect(mainSource).toContain('function notifyAgentContextChanged(force = false)')
    expect(mainSource).toContain('notifyAgentContextChanged(true)')
  })
})
