import { describe, expect, it } from 'vitest'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const hydrologyMainPath = path.resolve(__dirname, '../../src/renderer/pages/hydrology-workbench/main.js')
const hydrologyStylesPath = path.resolve(__dirname, '../../src/renderer/pages/hydrology-workbench/styles.css')
const hydrologyTrendRendererPath = path.resolve(__dirname, '../../src/renderer/pages/hydrology-workbench/trend-renderer.js')
const hydrologyRealtimeActionsPath = path.resolve(__dirname, '../../src/renderer/pages/hydrology-workbench/realtime-actions.js')
const hydrologyRealtimeViewPath = path.resolve(__dirname, '../../src/renderer/pages/hydrology-workbench/realtime-view.js')
const hydrologyWorkbenchViewsPath = path.resolve(__dirname, '../../src/renderer/pages/hydrology-workbench/workbench-views.js')
const hydrologyReviewViewPath = path.resolve(__dirname, '../../src/renderer/pages/hydrology-workbench/review-view.js')

describe('hydrology workbench backend wiring', () => {
  it('loads and saves station data through the backend API bridge', () => {
    const source = fs.readFileSync(hydrologyMainPath, 'utf-8')
    const styles = fs.readFileSync(hydrologyStylesPath, 'utf-8')
    const trendRenderer = fs.readFileSync(hydrologyTrendRendererPath, 'utf-8')
    const realtimeActions = fs.readFileSync(hydrologyRealtimeActionsPath, 'utf-8')
    const realtimeView = fs.readFileSync(hydrologyRealtimeViewPath, 'utf-8')
    const workbenchViews = fs.readFileSync(hydrologyWorkbenchViewsPath, 'utf-8')
    const reviewView = fs.readFileSync(hydrologyReviewViewPath, 'utf-8')

    expect(source).toContain('window.electronAPI?.listHydrologyStations')
    expect(source).toContain('await window.electronAPI.listHydrologyStations()')
    expect(source).toContain('window.electronAPI?.getHydrologyStation')
    expect(source).toContain('await window.electronAPI.getHydrologyStation(stationId)')
    expect(source).toContain('window.electronAPI?.saveHydrologyStation')
    expect(source).toContain('await window.electronAPI.saveHydrologyStation(nextStation)')
    expect(source).toContain('window.electronAPI?.deleteHydrologyStation')
    expect(source).toContain('await window.electronAPI.deleteHydrologyStation(stationId)')
    expect(source).toContain('loadRealtimeSlotsAction')
    expect(source).toContain('loadRealtimeSlotDetailAction')
    expect(source).toContain('loadRealtimeTrendAction')
    expect(source).toContain('applyRealtimeFiltersAction')
    expect(source).toContain('resetRealtimeFiltersAction')
    expect(realtimeActions).toContain('electronAPI?.listHydrologyRealtimeSlots')
    expect(realtimeActions).toContain('await electronAPI.listHydrologyRealtimeSlots({')
    expect(realtimeActions).toContain('electronAPI?.getHydrologyRealtimeSlotDetail')
    expect(realtimeActions).toContain('await electronAPI.getHydrologyRealtimeSlotDetail(slotId)')
    expect(realtimeActions).toContain('electronAPI?.listHydrologyRealtimeTrend')
    expect(realtimeActions).toContain('await electronAPI.listHydrologyRealtimeTrend({')
    expect(source).toContain('window.electronAPI?.seedHydrologyRealtimeData')
    expect(source).toContain('await window.electronAPI.seedHydrologyRealtimeData(station.id)')
    expect(source).toContain('window.electronAPI?.createHydrologyRealtimeObservation')
    expect(source).toContain('await window.electronAPI.createHydrologyRealtimeObservation({')
    expect(source).toContain('window.electronAPI?.updateHydrologyRealtimeObservation')
    expect(source).toContain('await window.electronAPI.updateHydrologyRealtimeObservation(payload)')
    expect(source).toContain('window.electronAPI?.deleteHydrologyRealtimeObservation')
    expect(source).toContain('await window.electronAPI.deleteHydrologyRealtimeObservation(payload.id)')
    expect(source).toContain('async function mutateRealtimeObservation(payload = {}, mode = \'update\')')
    expect(source).toContain('renderReviewView')
    expect(source).toContain("activeFunctionKey === 'review'")
    expect(source).toContain('window.electronAPI?.listHydrologyReviewTasks')
    expect(source).toContain('await window.electronAPI.listHydrologyReviewTasks({')
    expect(source).toContain('window.electronAPI?.runHydrologyQualityCheck')
    expect(source).toContain('await window.electronAPI.runHydrologyQualityCheck({')
    expect(source).toContain('window.electronAPI?.resolveHydrologyReviewTask')
    expect(source).toContain('await window.electronAPI.resolveHydrologyReviewTask({')
    expect(source).toContain('await loadStations()')
    expect(source).toContain('async function selectStation(stationId)')
    expect(source).toContain('function renderRealtimeView(station)')
    expect(source).toContain('function renderReviewTaskView(station)')
    expect(source).toContain('renderRealtimeDetailModal(realtimeState.slotDetail)')
    expect(source).toContain("tabContentEl.querySelectorAll('[data-review-page-action]').forEach((button) => {")
    expect(source).toContain("document.getElementById('reviewPageSizeSelect')?.addEventListener('change'")
    expect(source).toContain('async function loadRealtimeSlots()')
    expect(source).toContain('async function loadReviewTasks()')
    expect(source).toContain('async function runReviewQualityCheck()')
    expect(source).toContain('async function runSlotQualityCheck({ slotId, slotTime } = {})')
    expect(source).toContain('async function openReviewTaskSlot(taskId, slotTime)')
    expect(source).toContain('async function openReviewTaskBoard()')
    expect(source).toContain('const ruleConfigForm = document.getElementById(\'ruleConfigForm\')')
    expect(source).toContain('function renderRuleConfigForm(station)')
    expect(source).toContain('function collectRuleConfigFromForm()')
    expect(source).toContain('ruleConfigForm.addEventListener(\'submit\', async (event) => {')
    expect(source).toContain('document.getElementById(\'reviewClearSlotFocusBtn\')?.addEventListener(\'click\', async () => {')
    expect(source).toContain('fromTime: slotTime')
    expect(source).toContain('toTime: slotTime')
    expect(source).toContain('realtimeState.slotCheckResult = {')
    expect(source).toContain('realtimeState.slotCheckResult = null')
    expect(source).toContain("realtimeState.slotDetailSource = 'review'")
    expect(source).toContain("if (source === 'review') {")
    expect(source).toContain("activeFunctionKey = 'review'")
    expect(source).toContain('slot: slotResult?.slot || null')
    expect(source).toContain('function renderTrendPanel(')
    expect(source).toContain('async function loadRealtimeTrend()')
    expect(source).toContain('async function applyRealtimeFilters(formData)')
    expect(realtimeActions).toContain('export async function loadRealtimeSlotsAction(deps)')
    expect(realtimeActions).toContain('export async function loadRealtimeSlotDetailAction(slotId, deps)')
    expect(realtimeActions).toContain('export async function loadRealtimeTrendAction(deps)')
    expect(realtimeActions).toContain('export function resetRealtimeFiltersAction(deps)')
    expect(realtimeActions).toContain('export async function applyRealtimeFiltersAction(formData, deps)')
    expect(source).toContain("renderTrendPanelFromRenderer")
    expect(source).toContain("buildTrendChartSvgFromRenderer")
    expect(source).toContain("buildTrendOverviewSvgFromRenderer")
    expect(source).toContain("renderRealtimeViewSection")
    expect(source).toContain("bindTrendViewportInteractionsView")
    expect(source).toContain("renderStationTreeView")
    expect(source).toContain("renderFunctionTabsView")
    expect(source).toContain("renderHeaderView")
    expect(trendRenderer).toContain("data-trend-preset=")
    expect(trendRenderer).toContain("data-trend-zoom=")
    expect(trendRenderer).toContain("data-trend-series=")
    expect(trendRenderer).toContain("class=\"trend-axis-label\"")
    expect(trendRenderer).toContain("class=\"trend-axis-unit\"")
    expect(source).toContain("function getVisibleTrendRange(sortedSlots)")
    expect(source).toContain("function getTrendAxisLabelStrategy(range, innerWidth)")
    expect(source).toContain("function buildTrendAxisModel(range, innerWidth)")
    expect(source).toContain("function bindTrendChartHover()")
    expect(source).toContain("function bindTrendViewportInteractions(slots)")
    expect(source).toContain("function setTrendViewport(center, span, bounds)")
    expect(source).toContain("function zoomTrendView(direction, slots)")
    expect(trendRenderer).toContain("const axisModel = buildTrendAxisModel(range, innerWidth)")
    expect(trendRenderer).toContain("data-trend-hover-crosshair")
    expect(trendRenderer).toContain("data-trend-overview-window")
    expect(realtimeView).toContain("export function bindTrendViewportInteractionsView(slots, deps = {})")
    expect(realtimeView).toContain('export function renderSlotCheckResultModalView(result, deps = {})')
    expect(realtimeView).toContain('采用值来源：')
    expect(realtimeView).toContain('data-source-save')
    expect(realtimeView).toContain('data-source-delete')
    expect(realtimeView).toContain('data-source-create')
    expect(realtimeView).toContain('补录')
    expect(realtimeView).toContain('inline-observation-editor')
    expect(realtimeView).not.toContain('来源数据管理')
    expect(realtimeView).not.toContain('data-source-edit-time')
    expect(realtimeView).toContain('data-slot-review="${escapeAttribute(slot.id)}"')
    expect(realtimeView).toContain("tabContentEl.querySelectorAll('[data-slot-review]').forEach((button) => {")
    expect(realtimeView).toContain('await runSlotQualityCheck({')
    expect(realtimeView).not.toContain('人工修正值')
    expect(realtimeView).not.toContain('采用值修正')
    expect(realtimeView).toContain('id="slotCheckResultTitle"')
    expect(realtimeView).toContain('本次检查结果')
    expect(realtimeView).toContain('查看审核任务')
    expect(realtimeView).toContain('未生成审核任务。')
    expect(realtimeView).toContain("trendViewportBindingsControllerRef.current?.abort()")
    expect(realtimeView).toContain("const requestTrendRender = () =>")
    expect(realtimeView).toContain("const blockSelection = (event) =>")
    expect(realtimeView).toContain("querySelector('[data-trend-hover-card]')")
    expect(workbenchViews).toContain("export function renderStationTreeView({")
    expect(workbenchViews).toContain("export function renderFunctionTabsView({")
    expect(workbenchViews).toContain("export function renderHeaderView({")
    expect(workbenchViews).not.toContain('waterLevelSectionMinElevation')
    expect(workbenchViews).not.toContain('waterLevelRequireManualObservation')
    expect(reviewView).toContain("export function renderReviewView(station, reviewState, deps = {})")
    expect(reviewView).toContain('id="reviewRunCheckBtn"')
    expect(reviewView).toContain('review-slot-focus')
    expect(reviewView).toContain('data-review-page-action="prev"')
    expect(reviewView).toContain('id="reviewPageSizeSelect"')
    expect(reviewView).toContain('查看全部任务')
    expect(reviewView).toContain('本次规则命中结果')
    expect(reviewView).toContain('当前时槽本次审核未发现问题。')
    expect(reviewView).toContain('本时槽未发现问题，规则引擎已完成检查。')
    expect(reviewView).toContain('算法/证据摘要')
    expect(reviewView).toContain('计算指标')
    expect(reviewView).toContain('data-review-open-slot="${escapeHtml(selectedTask.id)}"')
    expect(reviewView).toContain('查看对应时槽')
    expect(styles).toContain('.compact-action {')
    expect(styles).toContain('.review-slot-focus {')
    expect(styles).toContain('.review-inline-summary.has-issue {')
    expect(styles).toContain('.rule-config-form-grid {')
    expect(styles).toContain('.slot-check-card {')
    expect(styles).toContain('.slot-check-summary.has-issue {')
    expect(styles).toContain("user-select: none")
    expect(trendRenderer).toContain("const height = 28")
    expect(source).not.toContain('window.confirm(')
    expect(source).toContain('function openDeleteConfirm(station)')
    expect(source).toContain('function showCreateStationForm()')
  })
})
